services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5441:5432"